-- ============================================================
-- Migration 056: drop untriggered rows from ta_signals
--
-- WHAT AN UNTRIGGERED ROW IS
--   Each indicator writes one row per symbol per day recording two things:
--   whether its condition fired (`triggered`) and the number it measured
--   (`value`). `rsi_oversold` asks "is RSI below 30?" -- on a calm day it
--   stores triggered=false, value=54. That "no" answer is an untriggered row.
--
-- WHY THEY GO
--   Nothing reads them. All three readers filter `triggered = true`:
--     dashboard/src/app/scanner/page.tsx        (which symbols fired today)
--     dashboard/src/app/api/scanner/route.ts    (same, for a picked date)
--     dashboard/src/lib/chart-payload.ts        (where to draw chart markers)
--   Swept the repo for views, functions and other consumers -- there are none.
--   Measured on 2026-08-28: 46,711 rows for the session, 8,597 triggered. The
--   82% answering "no" cost ~1.4 GB a year to store and were never queried.
--
--   What is given up: answering "what was FPT's ADX on 2025-03-14" by SELECT.
--   The value stays recomputable from ta_ohlcv, which is the source of record.
--   Not quite everything: ta_signals reaches back to 2022-12-28 while most
--   symbols hold ~604 OHLCV bars (from ~2024-03), so rows older than that are
--   unrecoverable. That is ~1,200 rows in total -- the volume is all recent.
--
-- ORDER MATTERS: DEPLOY THE CODE FIRST
--   scripts/compute_ta_signals.py must already be writing triggered-only
--   (`write_signals`) before this runs, or the nightly pass simply refills what
--   this deletes. That change is also what makes the deletion SAFE: it replaced
--   the plain upsert with delete-then-insert. The upsert used to keep history
--   honest by OVERWRITING a stale `triggered = true` with the `false` that a
--   recomputation produced; with false rows no longer written, only the delete
--   stops a re-run leaving a signal the scanner still lists for a bar that no
--   longer produces it. Pinned by scripts/tests/test_signal_write.py.
--
-- HOW THE DELETION IS DONE
--   By scripts/prune_untriggered_signals.py, not by this file. A single delete
--   over ~6M rows exceeds the statement timeout that a bare count(*) on this
--   table already hits, so the work has to be broken up and committed in
--   pieces. plpgsql can do that with COMMIT inside a procedure, but the
--   Supabase SQL editor runs a script INSIDE a transaction block -- the same
--   reason `vacuum` fails there -- and a procedure cannot COMMIT inside one.
--   Rather than ship a procedure that errors in the one place these migrations
--   are applied, the loop lives in the script, where the service-role plumbing
--   already is: one date per request, idempotent, resumable, with --dry-run.
--
--   The script deletes optimistically (one unbounded delete per date) and falls
--   back to symbol chunks on a 57014 timeout, halving until each bite lands.
--   Chunking by symbol keeps it on the primary key, whose columns are
--   (date, symbol, indicator).
--
--   Run it BEFORE this migration:
--     cd scripts && python3 prune_untriggered_signals.py --dry-run
--     cd scripts && python3 prune_untriggered_signals.py
--
-- The row count drops ~82%, so the planner's stats are badly stale by the time
-- the script finishes. This is what this migration is FOR -- everything above is
-- the record of why the rows went.
analyze ta_signals;

-- ------------------------------------------------------------
-- AFTERWARDS, BY HAND (neither can run inside a transaction)
--
--   DELETE alone does not return space to the filesystem -- Postgres marks it
--   reusable, so the table stops growing but the dashboard figure stays put.
--   That is fine if you only care about growth. To actually shrink it:
--
--     vacuum full analyze ta_signals;
--
--   VACUUM FULL takes an ACCESS EXCLUSIVE lock and rewrites the table, so it
--   needs free space for a second copy and blocks readers while it runs. Do it
--   outside market hours. `vacuum ta_signals;` is the non-blocking alternative
--   that reclaims for reuse without shrinking.
-- ------------------------------------------------------------

-- Optional, NOT applied: make the invariant enforceable at the DB level.
--
--     alter table ta_signals add constraint ta_signals_triggered_only
--       check (triggered);
--
-- Left off deliberately. It would turn a future writer that forgets the filter
-- into a failed chunk -- loud, which this project generally prefers -- but the
-- blast radius is the whole nightly pass failing over rows that are merely
-- redundant. The Python write path is the single writer and is pinned by test.
