"""free-vnstock item_id  ->  paid-tier metric_id, PROVEN BY VALUE.

The free package (which runs in CI) and the sponsor package (which does not)
name the same financial line differently: free says `cash`, the store holds
`BS_CASH`; free says `current_assets`, the store holds `BS_SHORT_TERM_ASSETS`.
The transform is not mechanical, so the mapping has to be established rather
than guessed.

IT WAS ESTABLISHED BY MATCHING NUMBERS, NOT NAMES. We already hold sponsor data
for ~1,750 symbols, so for every candidate pair the two series were compared
across every shared quarter on 20 deliberately diverse symbols (industrials, a
developer, two banks, two brokers, an insurer). A pair is recorded only when it
agreed on at least 85% of shared quarters with no better-supported rival, and
both series carried at least two distinct non-zero values — an all-zero series
matches everything and proves nothing.

Three things this caught that a by-hand mapping would not have:

  * `accounts_receivable` is NOT the rubric's short-term receivables. AGG 2026-Q2:
    1,028bn against the correct 78.3bn (`trade_accounts_receivable`).
  * ZERO TOLERANCE WAS TOO STRICT at first. `cost_of_sales` is exact on 18 of 19
    symbols; AGG alone has one sign-flipped quarter (2025-Q3), a provider glitch,
    not a mapping error. A single bad quarter must not veto a mapping.
  * `BS_SHORT_TERM_INVESTMENTS` has NO free equivalent — free reports 0 where the
    sponsor tier reports 20,128bn for FPT. It is absent below, deliberately.

TWO LIMITS OF THE FREE FEED, both measured:
  1. It returns EIGHT QUARTERS per request; the store holds 34. Upserting keeps
     the older quarters intact, so history is preserved for symbols we already
     have — but a brand-new symbol accumulates depth one quarter at a time.
  2. On the quarters free does return, coverage matches the sponsor tier on 47
     of 49 mapped ids. The two exceptions differ by ~6%
     (BS_LONG_TERM_RECEIVABLES, IS_SELLING_EXPENSES).

`support` is how many of the 20 symbols corroborated the pair. A low number is
not a wrong mapping — many balance-sheet lines are legitimately zero for most
companies — but it is thinner evidence, so it is recorded rather than hidden.

Regenerate with scripts/tools/discover_metric_map.py.
"""

# metric_id -> (free item_id, statement, symbols corroborating)
FREE_TO_PAID: dict[str, tuple[str, str, int]] = {
    "BS_ACCRUED_EXPENSES": ("accrued_expenses", "balance", 18),
    "BS_ACCUMULATED_RETAINED_EARNING_AT_THE_END_OF_THE_PREVIOUS_PERIOD": ("beginning_accumulated_undistributed_earnings", "balance", 16),
    "BS_ADVANCES": ("advance", "balance", 2),
    "BS_ADVANCES_FROM_CUSTOMERS": ("advances_from_customers", "balance", 18),
    "BS_ASSETS_AWAITING_RESOLUTION": ("shortage_of_current_assets_waiting_for_solution", "balance", 2),
    "BS_ASSET_REVALUATION_DIFFERENCES": ("differences_upon_asset_revaluation", "balance", 2),
    "BS_AVAILABLE_FOR_SALE_FINANCIAL_ASSETS_AFS": ("available_for_sale_financial_assets_afs", "balance", 2),
    "BS_AVAILABLE_FOR_SALE_SECURITIES": ("available_for_sales_securities", "balance", 2),
    "BS_BALANCES_WITH_SBV": ("balances_with_the_sbv", "balance", 2),
    "BS_BONUS_AND_WELFARE_FUND": ("bonus_and_welfare_funds", "balance", 14),
    "BS_BORROWINGS_FROM_CREDIT_INSTITUTIONS": ("loans_from_other_credit_institutions", "balance", 2),
    "BS_CAPITAL_CONSTRUCTION_IN_PROGRESS": ("construction_in_progress", "balance", 18),
    "BS_CAPITAL_CONTRIBUTION_JOINT_VENTURES": ("investments_in_joint_venture", "balance", 1),
    "BS_CAPITAL_FROM_OWNERS": ("common_shares", "balance", 15),
    "BS_CASH": ("cash", "balance", 18),
    "BS_CASH_AND_PRECIOUS_METALS": ("cash_and_cash_equivalents", "balance", 18),
    "BS_CASH_EQUIVALENTS": ("cash_equivalents", "balance", 17),
    "BS_CHARTER_CAPITAL": ("paid_in_capital", "balance", 15),
    "BS_CHARTER_CAPITAL_AND_FUNDS": ("capital", "balance", 2),
    "BS_COMMITMENTS_TO_BUY_FX": ("foreign_exchange_buying_commitments", "balance", 2),
    "BS_COMMITMENTS_TO_SELL_FX": ("foreign_exchange_selling_commitments", "balance", 2),
    "BS_COMPULSORY_RESERVES": ("statutory_reserve", "balance", 1),
    "BS_CONSTRUCTION_IN_PROGRESS": ("long_term_incomplete_assets", "balance", 18),
    "BS_CONVERTIBLE_BONDS": ("convertible_bonds", "balance", 1),
    "BS_CUSTOMER_DEPOSITS": ("deposits_from_customers", "balance", 2),
    "BS_DEBT_PURCHASES_GROSS": ("debt_buying", "balance", 1),
    "BS_DEDUCTIBLE_VALUE_ADDED_TAX": ("vat_to_be_claimed", "balance", 15),
    "BS_DEFERRED_TAX_ASSETS": ("deferred_income_tax_assets", "balance", 16),
    "BS_DEFERRED_TAX_LIABILITIES": ("deferred_income_tax_liabilities", "balance", 14),
    "BS_DERIVATIVES_AND_OTHER_FINANCIAL_ASSETS": ("derivatives_and_other_financial_assets", "balance", 1),
    "BS_DERIVATIVES_AND_OTHER_FINANCIAL_LIABILITIES": ("derivatives_and_other_financial_liabilities", "balance", 2),
    "BS_DUE_TO_GOVERNMENT_AND_SBV": ("due_to_gov_and_loans_from_sbv", "balance", 2),
    "BS_EMPLOYEE_WELFARE_PAYABLES": ("employees_welfare_payable_to_authorities", "balance", 1),
    "BS_EQUITY": ("owners_equity", "balance", 20),
    "BS_FINANCE_LEASE_FIXED_ASSETS": ("finance_lease_assets", "balance", 2),
    "BS_FIXED_ASSETS": ("fixed_assets", "balance", 20),
    "BS_FOREIGN_EXCHANGE_DIFFERENCES": ("foreign_exchange_differences", "balance", 6),
    "BS_FUNDS_AND_ENTRUSTED_INVESTMENTS": ("funds_received_from_gov_international_and_other_institutions", "balance", 1),
    "BS_FUND_FOR_TECHNOLOGY_DEVELOPMENT": ("technology_science_development_fund", "balance", 2),
    "BS_FVTPL_FINANCIAL_ASSETS": ("short_term_investments", "balance", 5),
    "BS_FX_COMMITMENTS": ("foreign_exchange_transactions_commitments", "balance", 2),
    "BS_GOODWILL": ("goodwill", "balance", 7),
    "BS_HELD_TO_MATURITY_INVESTMENTS": ("held_to_maturity_investment", "balance", 9),
    "BS_HELD_TO_MATURITY_SECURITIES": ("held_to_maturity_securities", "balance", 2),
    "BS_INSURANCE_CONTRACT_PAYABLE": ("payables_from_insurance_contract", "balance", 1),
    "BS_INSURANCE_CONTRACT_RECEIVABLES": ("receivable_from_insurance_contract", "balance", 1),
    "BS_INTANGIBLE_FIXED_ASSETS": ("intangible_fixed_assets", "balance", 20),
    "BS_INTANGIBLE_FIXED_ASSETS_ACCUMULATED_DEPRECIATION": ("accumulated_amortization", "balance", 2),
    "BS_INTEREST_AND_FEE_PAYABLES": ("accrued_interest_and_fee_payables", "balance", 2),
    "BS_INTEREST_AND_FEE_RECEIVABLES": ("accrued_interest_and_fee_receivables", "balance", 2),
    "BS_INVENTORIES": ("inventories_net", "balance", 15),
    "BS_INVENTORIES_GROSS": ("inventories", "balance", 16),
    "BS_INVESTMENTS_IN_ASSOCIATES": ("investments_in_associates", "balance", 2),
    "BS_INVESTMENTS_IN_JOINT_VENTURES": ("investments_in_associates", "balance", 11),
    "BS_INVESTMENT_AND_DEVELOPMENT_FUND": ("investment_and_development_funds", "balance", 10),
    "BS_INVESTMENT_CAPITAL_FROM_OWNERS": ("shareholders_equity", "balance", 2),
    "BS_INVESTMENT_PROPERTIES": ("investment_properties", "balance", 11),
    "BS_INVESTMENT_PROPERTIES_ACCUMULATED_DEPRECIATION": ("accumulated_depreciation", "balance", 11),
    "BS_INVESTMENT_PROPERTIES_COST": ("cost", "balance", 8),
    "BS_INVESTMENT_SECURITIES": ("investment_securities", "balance", 2),
    "BS_LC_COMMITMENTS": ("letters_of_credit_commitments", "balance", 2),
    "BS_LOANS": ("loans", "balance", 2),
    "BS_LOANS_TO_CREDIT_INSTITUTIONS": ("loans_to_other_credit_institutions", "balance", 2),
    "BS_LOANS_TO_CUSTOMERS": ("loans_and_advances_to_customers_net", "balance", 2),
    "BS_LOANS_TO_CUSTOMERS_GROSS": ("loans_and_advances_to_customers", "balance", 2),
    "BS_LONG_TERM_ACCRUED_EXPENSES": ("long_term_accrued_expenses", "balance", 3),
    "BS_LONG_TERM_ADVANCES_FROM_CUSTOMERS": ("long_term_advances_from_customers", "balance", 1),
    "BS_LONG_TERM_ASSETS": ("long_term_assets", "balance", 18),
    "BS_LONG_TERM_BORROWINGS": ("long_term_borrowings", "balance", 11),
    "BS_LONG_TERM_EQUIPMENT_SUPPLIES_SPARE_PARTS": ("long_term_equipment_material_and_spare_parts", "balance", 4),
    "BS_LONG_TERM_INVESTMENTS": ("long_term_investments", "balance", 15),
    "BS_LONG_TERM_LIABILITIES": ("long_term_liabilities", "balance", 17),
    "BS_LONG_TERM_LOAN_RECEIVABLES": ("long_term_loans_receivables", "balance", 4),
    "BS_LONG_TERM_PLEDGED_ASSETS": ("long_term_collaterals", "balance", 2),
    "BS_LONG_TERM_PREPAYMENTS": ("long_term_prepayments", "balance", 18),
    "BS_LONG_TERM_PREPAYMENTS_TO_SUPPLIERS": ("long_term_prepayments_to_suppliers", "balance", 4),
    "BS_LONG_TERM_PRODUCTION_IN_PROGRESS": ("long_term_cost_of_work_in_progress", "balance", 2),
    "BS_LONG_TERM_PROVISIONS": ("provision_for_long_term_liabilities", "balance", 11),
    "BS_LONG_TERM_RECEIVABLES": ("long_term_trade_receivables", "balance", 15),
    "BS_LONG_TERM_TRADE_PAYABLES": ("long_term_trade_payables", "balance", 1),
    "BS_LONG_TERM_TRADE_RECEIVABLES": ("long_term_trade_receivables_from_customers", "balance", 3),
    "BS_LONG_TERM_UNEARNED_REVENUE": ("deferred_revenue", "balance", 7),
    "BS_MINORITY_INTEREST": ("minority_interests", "balance", 16),
    "BS_OFFICE_SUPPLIES_TOOLS": ("tools_and_equipments", "balance", 2),
    "BS_OFF_BAD_DEBTS_WRITTEN_OFF": ("doubtful_debts_written_off", "balance", 1),
    "BS_OFF_CUSTOMER_DEPOSITS": ("customerss_deposits", "balance", 2),
    "BS_OFF_FIRM_ENTITLED_FINANCIAL_ASSETS": ("financial_assets_with_rights_entitled_of_the_securities_company", "balance", 1),
    "BS_OFF_FIRM_LISTED_FINANCIAL_ASSETS": ("financial_assets_of_company_listed_on_stock_exchanges_or_registered_at_the_vsd", "balance", 2),
    "BS_OFF_FIRM_UNREGISTERED_FINANCIAL_ASSETS": ("financial_assets_which_have_not_been_registered_at_vsd_of_the_securities_company", "balance", 2),
    "BS_OFF_FIRM_UNTRADED_FINANCIAL_ASSETS": ("financial_assets_deposited_at_vsd_and_not_yet_available_for_transaction", "balance", 2),
    "BS_OFF_FOREIGN_CURRENCIES": ("foreign_currencies", "balance", 2),
    "BS_OFF_GENERAL_TRADING_DEPOSITS": ("investors_synthesizing_deposits_for_securities_trading_activities", "balance", 1),
    "BS_OFF_INVESTOR_AWAITING_FINANCIAL_ASSETS": ("financial_assets_with_pending_receipt_of_the_assets", "balance", 2),
    "BS_OFF_INVESTOR_ENTITLED_FINANCIAL_ASSETS": ("enititled_financial_assets_of_investors", "balance", 1),
    "BS_OFF_INVESTOR_LISTED_AWAITING_SETTLEMENT": ("financial_assets_with_pending_payment", "balance", 2),
    "BS_OFF_INVESTOR_LISTED_BLOCKED": ("financial_assets_frozen_on_custody", "balance", 2),
    "BS_OFF_INVESTOR_LISTED_FINANCIAL_ASSETS": ("financial_assets_listed_registered_at_vsd_of_the_investor", "balance", 2),
    "BS_OFF_INVESTOR_LISTED_FREELY_TRADABLE": ("financial_assets_that_can_be_freely_traded", "balance", 2),
    "BS_OFF_INVESTOR_LISTED_PLEDGED": ("collateral_financial_assets", "balance", 2),
    "BS_OFF_INVESTOR_LISTED_RESTRICTED": ("financial_assets_of_which_trading_is_restricted", "balance", 2),
    "BS_OFF_INVESTOR_TRADING_DEPOSITS": ("customerss_deposits_for_securities_trading", "balance", 2),
    "BS_OFF_INVESTOR_UNREGISTERED_FINANCIAL_ASSETS": ("financial_assets_which_have_not_been_registered_at_vsd_of_investor", "balance", 1),
    "BS_OFF_INVESTOR_UNTRADED_FINANCIAL_ASSETS": ("financial_assets_deposited_at_vsd_not_yet_available_for_transaction", "balance", 1),
    "BS_OFF_INVESTOR_UNTRADED_FREELY_TRADABLE": ("fa_deposited_at_vsd_not_yet_available_for_transaction_freely_traded", "balance", 1),
    "BS_OFF_OUTSTANDING_SHARES": ("outstanding_shares_volume", "balance", 2),
    "BS_OFF_PAYABLES_DIVIDENDS_PRINCIPAL_INTEREST": ("dividend_bond_principal_and_interest_payables", "balance", 2),
    "BS_OFF_PAYABLES_ISSUER": ("payable_to_securities_issuers", "balance", 1),
    "BS_OTHER_ASSETS_DETAIL": ("other_assets", "balance", 2),
    "BS_OTHER_CAPITAL": ("owners_other_capital", "balance", 6),
    "BS_OTHER_COMMITMENTS": ("other_commitments", "balance", 2),
    "BS_OTHER_GUARANTEES": ("other_guarantee", "balance", 2),
    "BS_OTHER_LONG_TERM_ASSETS_DETAIL": ("other_long_term_assets", "balance", 10),
    "BS_OTHER_LONG_TERM_INVESTMENTS": ("other_long_term_investments", "balance", 12),
    "BS_OTHER_LONG_TERM_LIABILITIES": ("other_long_term_payables", "balance", 13),
    "BS_OTHER_LONG_TERM_RECEIVABLES": ("other_long_term_receivables", "balance", 1),
    "BS_OTHER_LONG_TERM_RECEIVABLES_LEGACY": ("other_long_term_receivables", "balance", 16),
    "BS_OTHER_PAYABLES": ("other_payables", "balance", 18),
    "BS_OTHER_PAYABLES_AND_LIABILITIES": ("other_liabilities", "balance", 2),
    "BS_OTHER_PAYABLES_TO_SUPPLIERS": ("payables_to_suppliers", "balance", 1),
    "BS_OTHER_RECEIVABLES": ("other_receivables", "balance", 17),
    "BS_OTHER_RECEIVABLES_OF_CUSTOMERS": ("other_receivable_from_customers", "balance", 1),
    "BS_OTHER_RESERVES": ("other_funds", "balance", 3),
    "BS_OTHER_SHORT_TERM_ASSETS_DETAIL": ("others", "balance", 1),
    "BS_OWNERS_EQUITY": ("owners_equity", "balance", 15),
    "BS_PAYABLES_GOVERNMENT_BONDS_TRADING": ("government_bonds_purchased_for_resale", "balance", 1),
    "BS_PAYABLES_SECURITIES_TRADING": ("payables_to_securities_trading", "balance", 2),
    "BS_PAYABLE_TO_EMPLOYEES": ("payable_to_employees", "balance", 16),
    "BS_PLACEMENTS_AND_LOANS_TO_CREDIT_INSTITUTIONS": ("placements_with_and_loans_to_other_credit_institutions", "balance", 2),
    "BS_PLACEMENTS_FROM_CREDIT_INSTITUTIONS": ("deposits_and_loans_from_other_credit_institutions", "balance", 2),
    "BS_PLACEMENTS_WITH_CREDIT_INSTITUTIONS": ("balances_with_other_credit_institutions", "balance", 2),
    "BS_PLEDGED_ASSETS_MORTGAGES_SECURITY_DEPOSITS_IN_SHORT_TERM": ("short_term_collaterals", "balance", 1),
    "BS_PREPAYMENTS_TO_SUPPLIERS": ("prepayments_to_suppliers", "balance", 18),
    "BS_PRICE_STABILIZATION_FUND": ("price_stabilization_fund", "balance", 1),
    "BS_PROFIT_THIS_PERIOD": ("current_period_undistributed_earnings", "balance", 18),
    "BS_PROVISIONS_FOR_IMPAIRMENT_LOSS_OF_FINANCIAL_ASSETS_AND_MORTGAGES": ("provision_for_diminution", "balance", 3),
    "BS_PROVISION_CREDIT_INSTITUTIONS": ("allowance_for_balances_with_and_loans_to_other_credit_institutions", "balance", 2),
    "BS_PROVISION_DEBT_PURCHASES": ("provision_for_losses_on_debt_buying", "balance", 1),
    "BS_PROVISION_DOUBTFUL_DEBTS": ("provision_for_doubtful_debts", "balance", 13),
    "BS_PROVISION_FOR_DOUBTFUL_DEBTS": ("provision_for_short_term_receivables", "balance", 2),
    "BS_PROVISION_INVENTORIES": ("provision_for_decline_in_inventories", "balance", 11),
    "BS_PROVISION_INVESTMENT_SECURITIES": ("provision_for_diminution_in_value_of_investment_securities", "balance", 2),
    "BS_PROVISION_LOANS_TO_CUSTOMERS": ("less_provision_for_losses_on_loans_and_advances_to_customers", "balance", 2),
    "BS_PROVISION_LONG_TERM_INVESTMENTS": ("provision_for_long_term_investments", "balance", 6),
    "BS_PROVISION_OTHER_ASSETS": ("provision_for_other_assets", "balance", 2),
    "BS_PROVISION_TRADING_SECURITIES": ("less_provision_for_diminution_in_value_of_trading_securities", "balance", 2),
    "BS_RECEIVABLES": ("other_receivables", "balance", 2),
    "BS_RECEIVABLES_FROM_DISPOSAL_OF_FINANCIAL_ASSETS": ("account_receivables", "balance", 2),
    "BS_RECEIVABLES_UNDER_CONSTRUCTION_CONTRACTS": ("construction_contract_in_progress_receivables", "balance", 2),
    "BS_REINSURANCE_ASSETS": ("reinsurance_assets", "balance", 1),
    "BS_REINSURANCE_ASSETS_FROM_CLAIM_RESERVES": ("provision_for_claim_from_outward_reinsurance", "balance", 1),
    "BS_REINSURANCE_ASSETS_FROM_UNEARNED_PREMIUM_RESERVES": ("provision_for_premium_outward_reinsurance", "balance", 1),
    "BS_RESERVES": ("reserves", "balance", 2),
    "BS_RETAINED_EARNINGS": ("undistributed_earnings", "balance", 17),
    "BS_SERVICE_RELATED_RECEIVABLE": ("receivables_form_services_provided_by_the_stock_company", "balance", 2),
    "BS_SETTLEMENT_ASSISTANCE_FUND": ("payments_to_settlement_assistance_fund", "balance", 1),
    "BS_SHARE_PREMIUM": ("share_premium", "balance", 8),
    "BS_SHORT_TERM_ASSETS": ("current_assets", "balance", 18),
    "BS_SHORT_TERM_BORROWINGS": ("short_term_borrowings", "balance", 17),
    "BS_SHORT_TERM_BORROWINGS_DETAIL": ("short_term_borrowings", "balance", 2),
    "BS_SHORT_TERM_DEPOSITS_RECEIVED": ("short_term_collaterals_received", "balance", 1),
    "BS_SHORT_TERM_FINANCIAL_ASSETS": ("short_term_financial_assets", "balance", 2),
    "BS_SHORT_TERM_LIABILITIES": ("current_liabilities", "balance", 18),
    "BS_SHORT_TERM_LOAN_RECEIVABLES": ("short_term_loans_receivables", "balance", 9),
    "BS_SHORT_TERM_PAYABLES_FOR_CONSTRUCTION_CONTRACT_PROGRESS": ("construction_contract_in_progress_payables", "balance", 1),
    "BS_SHORT_TERM_PREPAYMENTS": ("short_term_prepayments", "balance", 17),
    "BS_SHORT_TERM_PROVISIONS": ("provision_for_st_liabilities", "balance", 11),
    "BS_SHORT_TERM_RECEIVABLES": ("accounts_receivable", "balance", 18),
    "BS_SHORT_TERM_UNEARNED_REVENUE": ("short_term_unrealized_revenue", "balance", 13),
    "BS_SWAP_COMMITMENTS": ("swap_commitments", "balance", 2),
    "BS_TANGIBLE_FIXED_ASSETS": ("tangible_fixed_assets", "balance", 20),
    "BS_TAXES_AND_OTHER_PAYABLES_TO_STATE_AUTHORITIES": ("taxes_and_other_payable_to_state_budget", "balance", 18),
    "BS_TAXES_AND_OTHER_RECEIVABLES_FROM_STATE_AUTHORITIES": ("other_taxes_receivable", "balance", 16),
    "BS_TOTAL_ASSETS": ("total_assets", "balance", 20),
    "BS_TOTAL_LIABILITIES": ("liabilities", "balance", 18),
    "BS_TOTAL_LIABILITIES_AND_EQUITY": ("total_assets", "balance", 20),
    "BS_TRADE_ACCOUNTS_PAYABLE": ("trade_accounts_payable", "balance", 18),
    "BS_TRADE_RECEIVABLES": ("trade_accounts_receivable", "balance", 16),
    "BS_TRADING_SECURITIES": ("trading_securities_net", "balance", 2),
    "BS_TRADING_SECURITIES_GROSS": ("trading_securities", "balance", 2),
    "BS_TREASURY_SHARES": ("treasury_shares", "balance", 2),
    "BS_UNALLOCATED_COMMISSIONS_EXPENSES": ("undistributed_commission_expenses", "balance", 1),
    "BS_UNEARNED_COMMISSION_REVENUES": ("unearned_commission_income", "balance", 1),
    "BS_UNREALIZED_PROFITS": ("unrealized_gain", "balance", 2),
    "BS_VALUABLE_PAPERS_ISSUED": ("convertible_bonds_cds_and_other_valuable_papers_issued", "balance", 2),
    "CF_ACCRUED_EXPENSES_CHANGE": ("increase_decrease_in_payable_expenses_excluding_interest_expenses", "cashflow", 2),
    "CF_ADJUSTMENTS": ("adjustment", "cashflow", 2),
    "CF_AFS_CHANGE": ("increase_decrease_in_available_for_sale_financial_assets", "cashflow", 2),
    "CF_AFS_RECLASS_GAINS": ("profit_recognized_when_reclassification_of_afs_is_made_and_fair_value_is_used_for_revaluation", "cashflow", 1),
    "CF_BROKERAGE_SECURITIES_PURCHASE_PAYMENTS": ("cash_outflow_from_securities_purchase_broking", "cashflow", 2),
    "CF_BROKERAGE_SECURITIES_SALE_PROCEEDS": ("cash_inflow_from_securities_sales_broking", "cashflow", 2),
    "CF_BROKERAGE_TRUST_NET_FLOWS": ("net_cash_inflows_outflows_from_brokerage_and_trust_activities", "cashflow", 2),
    "CF_BROKER_MANAGED_DEPOSITS_END": ("investors_deposit_for_securities_transaction_by_securities_company_managed_method", "cashflow", 2),
    "CF_CASH_AND_CASH_EQUIVALENTS_AT_BEGINNING_OF_PERIOD_RESTATED": ("other_adjustments", "cashflow", 2),
    "CF_CASH_AND_CASH_EQUIVALENTS_AT_END_OF_PERIOD": ("cash_and_cash_equivalents_at_the_end_of_period", "cashflow", 18),
    "CF_CASH_AND_CASH_EQUIVALENTS_AT_END_OF_PERIOD_RESTATED": ("increase_decrease_in_trading_securities", "cashflow", 4),
    "CF_CASH_BANK_BALANCES_BEGIN": ("cash_and_bank_deposit_at_the_beginning_of_the_period", "cashflow", 2),
    "CF_CASH_BANK_BALANCES_END": ("cash_and_bank_deposit_during_the_period", "cashflow", 2),
    "CF_CASH_EQUIVALENTS_END": ("cash_equivalents", "cashflow", 1),
    "CF_CHANGES_IN_OPERATING_ASSETS_AND_LIABILITIES": ("change_in_assets_and_operating_liabilities_before_2016", "cashflow", 2),
    "CF_CLEARING_DEPOSITS_END": ("deposit_for_securities_clearing", "cashflow", 1),
    "CF_COLLECTIONS_FROM_BAD_DEBTS_WRITTEN_OFF": ("receipts_from_debts_written_off_or_paid_off_by_risk_fund", "cashflow", 2),
    "CF_COLLECTION_OF_LOANS": ("collection_of_loans_proceeds_from_sales_of_debts_instruments", "cashflow", 16),
    "CF_CORPORATE_INCOME_TAX_PAID": ("payments_for_corporate_income_tax", "cashflow", 2),
    "CF_CUSTOMER_DEPOSITORY_FEE_PAYMENTS": ("cash_paid_for_depository_fee_of_clients", "cashflow", 2),
    "CF_CUSTOMER_GENERAL_DEPOSITS_END": ("customers_general_deposit_for_securities_transactions", "cashflow", 1),
    "CF_CUSTOMER_SECURITIES_SETTLEMENT_PAYMENTS": ("cash_outflow_on_securities_transaction_settlement_of_clients", "cashflow", 1),
    "CF_CUSTOMER_SECURITIES_SETTLEMENT_RECEIPTS": ("cash_received_for_the_purpose_of_transaction_of_clients", "cashflow", 2),
    "CF_DEPRECIATION_AMORTIZATION": ("amortization_of_goodwill", "cashflow", 2),
    "CF_DEPRECIATION_AND_AMORTISATION": ("depreciation_and_amortization", "cashflow", 18),
    "CF_DIVIDENDS_AND_INTEREST_RECEIVED": ("dividends_and_interest_received", "cashflow", 19),
    "CF_DIVIDENDS_PAID": ("dividends_paid", "cashflow", 18),
    "CF_DIVIDEND_INTEREST_RECEIVABLES_CHANGE": ("increase_decrease_in_receivable_from_interest_of_financial_assets", "cashflow", 1),
    "CF_EFFECT_OF_FOREIGN_EXCHANGE_DIFFERENCES": ("cash_and_cash_equivalents_at_the_beginning_of_period", "cashflow", 2),
    "CF_EMPLOYEE_PAYABLES_CHANGE": ("increase_decrease_in_payables_to_employees", "cashflow", 2),
    "CF_FOREIGN_EXCHANGE_LOSS_GAIN": ("unrealized_foreign_exchange_gain_loss", "cashflow", 15),
    "CF_FVTPL_CHANGE": ("increase_decrease_in_fair_value_through_profit_and_loss_financial_assets", "cashflow", 2),
    "CF_FVTPL_GAINS": ("profit_from_revaluation_of_fair_value_through_profit_and_loss_financial_assets", "cashflow", 2),
    "CF_FVTPL_LOSSES": ("loss_on_valuation_of_fair_value_through_profit_loss_financial_assets", "cashflow", 2),
    "CF_HTM_CHANGE": ("increase_decrease_in_held_to_marturity_investments", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_CUSTOMER_DEPOSITS": ("increase_decrease_in_deposits_from_customers", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_DERIVATIVES_AND_OTHER_FINANCIAL_ASSETS": ("increase_decrease_in_derivatives_and_other_financial_assets", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_DERIVATIVES_AND_OTHER_FINANCIAL_LIABILITIES": ("increase_decrease_in_derivatives_and_other_financial_liabilities", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_DUE_TO_GOVERNMENT_AND_SBV": ("increase_decrease_in_loans_from_the_state_and_sbv", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_FUNDS_AND_ENTRUSTED_INVESTMENTS": ("increase_decrease_in_funds_received_from_gov_international_and_other_institutions", "cashflow", 1),
    "CF_INCREASE_DECREASE_IN_INVENTORY": ("increase_decrease_in_inventories", "cashflow", 16),
    "CF_INCREASE_DECREASE_IN_LOANS_TO_CUSTOMERS": ("increase_decrease_in_loans_and_advances_to_customers", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_OTHER_OPERATING_ASSETS": ("increase_decrease_in_other_operating_assets", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_OTHER_OPERATING_LIABILITIES": ("increase_decrease_in_other_operating_liabilities", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_PAYABLES": ("increase_decrease_in_payables", "cashflow", 17),
    "CF_INCREASE_DECREASE_IN_PLACEMENTS_AND_BORROWINGS_FROM_CREDIT_INSTITUTIONS": ("increase_decrease_in_placements_and_loans_from_other_credit_institutions", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_PLACEMENTS_AND_LOANS_TO_CREDIT_INSTITUTIONS": ("increase_decrease_in_placements_with_and_loans_to_other_credit_institutions", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_PREPAID_EXPENSES": ("increase_decrease_in_prepaid_expenses", "cashflow", 18),
    "CF_INCREASE_DECREASE_IN_PROVISION_FOR_LOSSES": ("increase_decrease_in_provision_for_loan_losses", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_RECEIVABLES": ("increase_decrease_in_receivables", "cashflow", 17),
    "CF_INCREASE_DECREASE_IN_TRADING_SECURITIES": ("increase_decrease_in_trading_securities", "cashflow", 2),
    "CF_INCREASE_DECREASE_IN_VALUABLE_PAPERS_ISSUED": ("increase_decrease_in_valuable_papers_issued", "cashflow", 2),
    "CF_INTEREST_AND_SIMILAR_EXPENSES_PAID": ("interest_and_similar_payments", "cashflow", 2),
    "CF_INTEREST_AND_SIMILAR_INCOME_RECEIVED": ("interest_and_similar_receipts", "cashflow", 2),
    "CF_INTEREST_EXPENSE": ("interest_expense", "cashflow", 17),
    "CF_INTEREST_PAID": ("interest_paid", "cashflow", 18),
    "CF_INVESTOR_TRUST_RECEIPTS": ("cash_received_for_the_purpose_of_mandated_investment_of_clients", "cashflow", 2),
    "CF_ISSUER_DEPOSITS_END": ("issuing_organizations_deposit", "cashflow", 1),
    "CF_ISSUER_PAYMENTS": ("cash_paid_to_issuing_organizations", "cashflow", 1),
    "CF_ISSUER_RECEIPTS": ("cash_received_from_issuing_organizations", "cashflow", 1),
    "CF_LOANS_CHANGE": ("increase_decrease_in_loans_given", "cashflow", 2),
    "CF_LOANS_IMPAIRMENT_LOSSES": ("loss_on_the_decrease_in_value_of_loans_given", "cashflow", 1),
    "CF_LOANS_TO_OTHER_ENTITIES": ("loans_granted_purchases_of_debt_instruments", "cashflow", 16),
    "CF_LOSS_GAIN_FROM_INVESTMENT": ("profit_loss_from_investing_activities", "cashflow", 16),
    "CF_NET_CASH_FLOWS_DURING_THE_PERIOD": ("net_increase_decrease_in_cash_and_cash_equivalents", "cashflow", 2),
    "CF_NET_CASH_FLOWS_FROM_INVESTING_ACTIVITIES": ("net_cash_inflows_outflows_from_investing_activities", "cashflow", 18),
    "CF_NET_CASH_FLOWS_FROM_OPERATING_ACTIVITIES": ("net_cash_inflows_outflows_from_operating_activities", "cashflow", 18),
    "CF_NET_CASH_FLOWS_FROM_OPERATING_ACTIVITIES_BEFORE_TAX": ("net_cash_flows_from_operating_activities_before_cit", "cashflow", 2),
    "CF_NET_FEE_AND_COMMISSION_RECEIPTS": ("fees_and_commission_income_received", "cashflow", 2),
    "CF_NON_CASH_EXPENSES_INCREASE": ("increase_in_non_cash_expense", "cashflow", 2),
    "CF_NON_CASH_REVENUE_DECREASE": ("decrease_in_non_cash_revenue", "cashflow", 2),
    "CF_OPERATING_PROFIT_BEFORE_CHANGES_IN_WORKING_CAPITAL": ("operating_profit_loss_before_changes_in_working_capital", "cashflow", 18),
    "CF_OTHER_ASSETS_CHANGE": ("increase_decrease_in_other_assets", "cashflow", 2),
    "CF_OTHER_GAINS": ("other_profit", "cashflow", 1),
    "CF_OTHER_LOSSES": ("other_loss", "cashflow", 1),
    "CF_OTHER_OPERATING_RECEIPTS": ("other_operating_income", "cashflow", 2),
    "CF_OTHER_PAYMENTS_FOR_OPERATING_ACTIVITIES": ("other_payments_on_operating_activities", "cashflow", 13),
    "CF_OTHER_RECEIPTS": ("other_receivables", "cashflow", 2),
    "CF_OTHER_RECEIPTS_FROM_OPERATING_ACTIVITIES": ("other_receipts_from_operating_activities", "cashflow", 3),
    "CF_PAYMENTS_FOR_FINANCE_LEASES": ("finance_lease_principal_payments", "cashflow", 2),
    "CF_PAYMENTS_FOR_FIXED_ASSETS": ("purchases_of_fixed_assets_and_other_long_term_assets", "cashflow", 20),
    "CF_PAYMENTS_FOR_INVESTMENTS_IN_OTHER_ENTITIES": ("investments_in_other_entities", "cashflow", 14),
    "CF_PAYMENTS_FOR_SHARE_REPURCHASES": ("payments_for_share_returns_and_repurchases", "cashflow", 5),
    "CF_PAYMENTS_FROM_DISPOSAL_OF_FIXED_ASSETS": ("payments_on_disposal_of_fixed_assets", "cashflow", 2),
    "CF_PAYMENTS_FROM_DISPOSAL_OF_INVESTMENT_PROPERTIES": ("payments_on_disposal_of_investment_properties", "cashflow", 1),
    "CF_PAYMENTS_FROM_RESERVES": ("payment_from_reserves", "cashflow", 2),
    "CF_PAYMENTS_TO_EMPLOYEES_AND_FOR_ADMINISTRATIVE_EXPENSES": ("payments_to_employees_and_other_operating_expenses", "cashflow", 2),
    "CF_PROCEEDS_FROM_BORROWINGS": ("proceeds_from_loans", "cashflow", 16),
    "CF_PROCEEDS_FROM_DISPOSAL_OF_FIXED_ASSETS": ("proceeds_from_disposal_of_fixed_assets", "cashflow", 20),
    "CF_PROCEEDS_FROM_DISPOSAL_OF_INVESTMENT_PROPERTIES": ("proceeds_from_disposal_of_investment_properties", "cashflow", 1),
    "CF_PROCEEDS_FROM_INVESTMENTS_IN_OTHER_ENTITIES": ("proceeds_from_divestment_in_other_entities", "cashflow", 12),
    "CF_PROCEEDS_FROM_ISSUANCE_OF_SHARES": ("proceeds_from_issue_of_shares", "cashflow", 15),
    "CF_PROFIT_BEFORE_TAX": ("net_profit_loss_before_tax", "cashflow", 18),
    "CF_PROVISIONS": ("provisions", "cashflow", 18),
    "CF_RECEIVABLES_LEGACY": ("increase_decrease_in_receivable_before_2016", "cashflow", 2),
    "CF_REPAYMENT_OF_BORROWINGS": ("repayment_of_loans", "cashflow", 16),
    "CF_SERVICES_RECEIVABLES_CHANGE": ("increase_decrease_in_receivable_from_services_rendered", "cashflow", 2),
    "CF_TAX_PAYABLES_CHANGE": ("increase_decrease_in_tax_and_payables_to_authority", "cashflow", 2),
    "CF_TRADE_PAYABLES_CHANGE": ("increase_decrease_in_trade_payables", "cashflow", 2),
    "CF_WELFARE_PAYABLES_CHANGE": ("increase_decrease_in_contribution_to_employees_welfare", "cashflow", 1),
    "IS_ASSUMED_REINSURANCE_CLAIMS_EXPENSES": ("claim_expenses_for_reinsurance_assumed", "income", 1),
    "IS_A_REALISED_GAINS_ON_DISPOSALS_OF_FVTPL_FINANCIAL_ASSETS": ("income_from_selling_financial_assets_fvtpl", "income", 2),
    "IS_BASIC_EARNINGS_PER_SHARE": ("eps_basic_vnd", "income", 15),
    "IS_B_GAINS_FROM_REVALUATION_OF_FVTPL_FINANCIAL_ASSETS": ("fvtpl_revaluation_gain", "income", 2),
    "IS_CORPORATE_INCOME_TAX_EXPENSES": ("corporate_income_tax_expenses", "income", 14),
    "IS_COST_OF_GOODS_SOLD": ("cost_of_sales", "income", 15),
    "IS_CURRENT_CORPORATE_INCOME_TAX_EXPENSES": ("business_income_tax_current", "income", 19),
    "IS_C_DIVIDENDS_AND_INTEREST_INCOME_FROM_FVTPL_FINANCIAL_ASSETS": ("dividend_interest_from_fvtpl_financial_assets", "income", 2),
    "IS_DEFERRED_INCOME_TAX_EXPENSES": ("business_income_tax_deferred", "income", 17),
    "IS_DILUTED_EARNINGS_PER_SHARE": ("eps_diluted_vnd", "income", 10),
    "IS_DIRECT_INSURANCE_AND_MATURITY_CLAIMS_EXPENSES": ("claim_and_maturity_payment_expenses", "income", 1),
    "IS_DIRECT_INSURANCE_COMMISSION_EXPENSES": ("commissions", "income", 1),
    "IS_DIVIDENDS_INTEREST_INCOME_FROM_DEMAND_DEPOSITS": ("income_from_non_fixed_accrued_dividend_and_interest", "income", 2),
    "IS_FEE_AND_COMMISSION_EXPENSES": ("fees_and_commission_expenses", "income", 2),
    "IS_FEE_AND_COMMISSION_INCOME": ("fees_and_commission_income", "income", 2),
    "IS_FINANCIAL_ADVISORY_EXPENSES": ("expenses_for_financial_advisory_activities", "income", 2),
    "IS_FINANCIAL_EXPENSES": ("financial_expenses", "income", 16),
    "IS_FINANCIAL_INCOME": ("financial_income", "income", 15),
    "IS_GAINS_FROM_AVAILABLE_FOR_SALE_FINANCIAL_ASSETS_AFS": ("income_from_available_for_sales_assets_afs", "income", 2),
    "IS_GAINS_FROM_DISPOSAL_INVESTMENTS_IN_SUBSIDIARIES_ASSOCIATES_JOINT_VENTURES": ("gain_from_disposals_or_sales_of_investments_in_subsidiaries_associates_and_joint_ventures", "income", 1),
    "IS_GAINS_FROM_FINANCIAL_ASSETS_AT_FAIR_VALUE_THROUGH_PROFIT_OR_LOSS_FVTPL": ("income_from_financial_assets_recognized_through_profit_loss_fvtpl", "income", 2),
    "IS_GAINS_FROM_HELD_TO_MATURITY_INVESTMENTS": ("income_from_held_to_maturity_investment_htm", "income", 2),
    "IS_GENERAL_AND_ADMINISTRATIVE_EXPENSES": ("general_and_admin_expenses", "income", 14),
    "IS_GROSS_INSURANCE_OPERATING_PROFIT": ("gross_insurance_operating_profit", "income", 1),
    "IS_GROSS_PROFIT": ("gross_profit", "income", 17),
    "IS_GROSS_WRITTEN_PREMIUM": ("gross_written_premium", "income", 1),
    "IS_INCOME_FROM_CAPITAL_CONTRIBUTION_AND_LONG_TERM_INVESTMENTS": ("dividends_income", "income", 2),
    "IS_INCREASE_DECREASE_IN_CEDED_UNEARNED_PREMIUM_RESERVE": ("premium_deductions", "income", 1),
    "IS_INCREASE_DECREASE_IN_CLAIM_RESERVES": ("increase_decrease_in_claim_reserve", "income", 1),
    "IS_INCREASE_DECREASE_IN_CLAIM_RESERVES_RELATED_TO_REINSURANCE_CEDED": ("increase_decrease_in_claim_reserve_for_outward_insurance", "income", 1),
    "IS_INCREASE_DECREASE_IN_DIRECT_AND_ASSUMED_REINSURANCE_CLAIM_RESERVES": ("increase_decrease_in_claim_reserve_for_direct_insurance_and_inward_insurance", "income", 1),
    "IS_INCREASE_DECREASE_IN_MATHEMATICAL_RESERVE": ("increase_decrease_in_mathematic_reserves", "income", 1),
    "IS_INCREASE_DECREASE_IN_UNEARNED_PREMIUM_RESERVE": ("increase_decrease_in_unearned_premium_reserve", "income", 1),
    "IS_INSURANCE_PREMIUM": ("revenue_from_insurance_premium", "income", 1),
    "IS_INTEREST_AND_SIMILAR_EXPENSES": ("interest_and_similar_expenses", "income", 2),
    "IS_INTEREST_EXPENSES": ("interest_expenses", "income", 15),
    "IS_INTEREST_INCOME_AND_SIMILAR_INCOME": ("interest_and_similar_income", "income", 2),
    "IS_INTEREST_INCOME_FROM_LOANS_AND_RECEIVABLES": ("income_from_loans_and_receivables", "income", 2),
    "IS_LOSS_FROM_DISPOSAL_INVESTMENTS_IN_SUBSIDIARIES_ASSOCIATES_JOINT_VENTURES": ("loss_from_disposals_or_sales_of_investments_in_subsidiaries_associates_and_joint_ventures", "income", 1),
    "IS_LOSS_FROM_DISPOSAL_OF_FINANCIAL_ASSETS": ("loss_from_selling_financial_assets_fvtpl", "income", 2),
    "IS_LOSS_FROM_FVTPL_FINANCIAL_ASSETS": ("loss_from_financial_assets_recognized_through_profit_loss_fvtpl", "income", 2),
    "IS_MINORITY_INTEREST": ("minority_interest", "income", 3),
    "IS_NET_FEE_AND_COMMISSION_INCOME": ("net_fee_and_commission_income", "income", 2),
    "IS_NET_GAIN_LOSS_FROM_FOREIGN_CURRENCIES_AND_GOLD_TRADING": ("net_gain_loss_from_foreign_currency_and_gold_dealings", "income", 2),
    "IS_NET_GAIN_LOSS_FROM_INVESTMENT_SECURITIES": ("net_gain_loss_from_disposal_of_investment_securities", "income", 2),
    "IS_NET_GAIN_LOSS_FROM_TRADING_SECURITIES": ("net_gain_loss_from_trading_of_trading_securities", "income", 2),
    "IS_NET_INSURANCE_PREMIUM": ("net_revenue_of_insurance_premium", "income", 1),
    "IS_NET_INTEREST_INCOME": ("net_interest_income", "income", 2),
    "IS_NET_OTHER_INCOME": ("net_other_income_expenses", "income", 2),
    "IS_NET_PROFIT_AFTER_TAX": ("net_profit_loss_after_tax", "income", 19),
    "IS_NET_REVENUE": ("net_sales", "income", 17),
    "IS_OPERATING_EXPENSES": ("operating_expense", "income", 2),
    "IS_OPERATING_PROFIT": ("operating_profit_loss", "income", 15),
    "IS_OPERATING_PROFIT_BEFORE_PROVISION_FOR_CREDIT_LOSSES": ("net_operating_profit_before_allowance_for_credit_loss", "income", 2),
    "IS_OPERATING_RESULT": ("operating_profit_loss", "income", 2),
    "IS_OTHER_ACTIVITY_EXPENSES": ("expenses_from_other_activities", "income", 1),
    "IS_OTHER_ACTIVITY_INCOME": ("revenue_from_other_activities", "income", 1),
    "IS_OTHER_EXPENSES": ("other_expenses", "income", 17),
    "IS_OTHER_EXPENSES_INSURANCE": ("others", "income", 1),
    "IS_OTHER_INCOME": ("other_incomes", "income", 15),
    "IS_OTHER_INCOME_ABOUT_INVESTMENT": ("other_revenue_from_investments", "income", 1),
    "IS_OTHER_INVESTMENT_EXPENSES": ("other_investment_expenses", "income", 2),
    "IS_OTHER_PROFIT": ("net_other_income_expenses", "income", 15),
    "IS_OTHER_REVENUE": ("others_revenue", "income", 2),
    "IS_OTHER_SERVICES_EXPENSES": ("other_expenses", "income", 1),
    "IS_PROFIT_AFTER_TAX_FOR_SHAREHOLDERS_OF_PARENT_COMPANY": ("attributable_to_parent_company", "income", 19),
    "IS_PROFIT_AFTER_TAX_TAKEN_FROM_FUNDS": ("profit_after_tax_deducted_of_funds", "income", 1),
    "IS_PROFIT_BEFORE_TAX": ("net_accounting_profit_loss_before_tax", "income", 17),
    "IS_PROFIT_FORM_FINANCIAL_ACTIVITIES": ("profit_from_financial_activities", "income", 1),
    "IS_PROPRIETARY_TRADING_EXPENSES": ("proprietary_trading_services_expenses", "income", 2),
    "IS_PROVISION_EXPENSES_FOR_FINANCIAL_ASSETS_AND_DOUBTFUL_DEBTS": ("provision_for_losses_from_mortgage_assets_uncollectible_receivables_and_loan_expenses", "income", 1),
    "IS_PROVISION_FOR_CATASTROPHE_RESERVE": ("provision_for_catastrophe_reserve", "income", 1),
    "IS_PROVISION_FOR_CREDIT_LOSSES": ("provision_for_credit_losses", "income", 2),
    "IS_REALISED_PROFIT": ("realized_profit", "income", 2),
    "IS_REALIZED_AND_UNREALIZED_GAIN_FROM_CHANGES_IN_FOREIGN_EXCHANGE_RATES": ("realized_and_unrealized_foreign_exchange_gain", "income", 2),
    "IS_REALIZED_AND_UNREALIZED_LOSS_FROM_FOREIGN_EXCHANGE": ("realized_and_unrealized_foreign_exchange_loss", "income", 2),
    "IS_RECOVERIES_FROM_REINSURANCE_CEDED": ("claim_recoveries_from_outward_reinsurance", "income", 1),
    "IS_REINSURANCE_CEDED_PREMIUMS": ("reinsurance_premium_ceded", "income", 1),
    "IS_REINSURANCE_PREMIUM_ASSUMED": ("reinsurance_premium_assumed", "income", 1),
    "IS_RETAINED_CLAIMS": ("claim_expenses_on_retained_risks", "income", 1),
    "IS_REVENUE": ("sales", "income", 15),
    "IS_REVENUE_DEDUCTIONS": ("sales_deductions", "income", 11),
    "IS_REVENUE_FROM_BROKERAGE_SERVICES": ("revenue_in_brokerage_services", "income", 2),
    "IS_REVENUE_FROM_INVESTMENT_ADVISORY_SERVICES": ("revenue_in_financial_advisory_services", "income", 2),
    "IS_REVENUE_FROM_SECURITIES_CUSTODY_SERVICES": ("revenue_in_securities_custody_services", "income", 2),
    "IS_REVENUE_FROM_SECURITIES_INVESTMENT_ADVISORY_SERVICES": ("revenue_in_stock_investment_advisory_services", "income", 2),
    "IS_REVENUE_FROM_SHARE_ISSUE_GUARANTEE_AND_AGENCY_ACTIVITIES": ("revenue_in_underwriting_services", "income", 1),
    "IS_SALVAGES": ("salvages", "income", 1),
    "IS_SECURITIES_BROKERAGE_EXPENSES": ("brokerage_expenses", "income", 2),
    "IS_SECURITIES_CUSTODY_EXPENSES": ("investors_securities_depository_expenses", "income", 2),
    "IS_SECURITIES_INVESTMENT_ADVISORY_EXPENSES": ("expenses_for_securities_advisory", "income", 1),
    "IS_SELLING_EXPENSES": ("selling_expenses", "income", 15),
    "IS_SHARE_OF_ASSOCIATES_AND_JOINT_VENTURES_RESULT": ("gain_loss_from_joint_ventures_from_2015", "income", 10),
    "IS_SHARE_OF_PROFIT_IN_ASSOCIATES_AND_JOINT_VENTURES": ("shares_of_the_profit_of_associates_and_joint_ventures", "income", 1),
    "IS_TOTAL_DIRECT_INSURANCE_OPERATING_EXPENSES": ("total_direct_insurance_operating_expenses", "income", 1),
    "IS_TOTAL_INSURANCE_CLAIMS_EXPENSES": ("total_insurance_claim_settlement_expenses", "income", 1),
    "IS_TOTAL_NET_REVENUE_FROM_INSURANCE_BUSINESS": ("net_sales_from_insurance_business", "income", 1),
    "IS_TOTAL_OPERATING_INCOME": ("total_operating_income", "income", 2),
    "IS_TRANSACTION_COSTS_FOR_FVTPL_FINANCIAL_ASSETS": ("fvtpl_financial_assets_purchase_transaction_costs", "income", 2),
    "IS_UNDERWRITING_AND_ISSUANCE_AGENCY_EXPENSES": ("underwriting_securities_issuance_expenses", "income", 1),
    "IS_UNREALISED_PROFIT": ("unrealized_profit", "income", 2),
    "RT_BANK_CASA": ("casa_ratio", "ratio", 1),
    "RT_BANK_COF": ("avg_cost_of_financing", "ratio", 1),
    "RT_BANK_DEPOSIT_GROWTH": ("deposit_growth", "ratio", 1),
    "RT_BANK_EQUITY_TO_LOANS": ("equity_to_loans", "ratio", 1),
    "RT_BANK_LDR": ("ldr", "ratio", 1),
    "RT_BANK_LLR_TO_LOANS": ("loan_loss_reserve_to_loans", "ratio", 1),
    "RT_BANK_LOAN_GROWTH": ("loans_growth", "ratio", 1),
    "RT_BANK_NIM": ("net_interest_margin", "ratio", 1),
    "RT_BANK_NOII": ("non_interest_income", "ratio", 1),
    "RT_BANK_NPL": ("npl", "ratio", 1),
    "RT_BANK_NPL_COVERAGE": ("loan_loss_reserves_to_npls", "ratio", 1),
    "RT_BANK_PROVISION_TO_LOANS": ("provision_to_outstanding_loans", "ratio", 1),
    "RT_BANK_YIEA": ("avg_yield_on_earning_assets", "ratio", 1),
    "RT_EFF_ATR": ("asset_turnover", "ratio", 17),
    "RT_EFF_CASH_CYCLE": ("cash_cycle", "ratio", 17),
    "RT_EFF_DIO": ("days_inventory_outstanding", "ratio", 15),
    "RT_EFF_DPO": ("days_payable_outstanding", "ratio", 17),
    "RT_EFF_DSO": ("days_sales_outstanding", "ratio", 15),
    "RT_EFF_FATR": ("fixed_asset_turnover", "ratio", 17),
    "RT_LEV_DE": ("debt_to_equity", "ratio", 19),
    "RT_LEV_EQUITY_TO_ASSETS": ("equity_to_assets", "ratio", 1),
    "RT_LEV_EQUITY_TO_LIABILITIES": ("equity_to_liabilities", "ratio", 1),
    "RT_LEV_LOAN_EQUITY": ("debtPerEquity", "ratio", 18),
    "RT_LQD_CASH_RATIO": ("cash_ratio", "ratio", 18),
    "RT_LQD_CR": ("current_ratio", "ratio", 18),
    "RT_LQD_QR": ("quick_ratio", "ratio", 18),
    "RT_PRT_EBIT_MARGIN": ("ebit_margin", "ratio", 18),
    "RT_PRT_GROSS_MARGIN": ("gross_margin", "ratio", 19),
    "RT_PRT_NET_MARGIN": ("net_margin", "ratio", 19),
    "RT_PRT_PRE_TAX_MARGIN": ("pre_tax_profit_margin", "ratio", 18),
    "RT_PRT_ROA": ("roa", "ratio", 19),
    "RT_PRT_ROE": ("roe", "ratio", 19),
    "RT_PRT_ROIC": ("roic", "ratio", 18),
    "RT_VALUE_EBIT": ("ebit", "ratio", 18),
    "RT_VALUE_EBITDA": ("ebitda", "ratio", 18),
    "RT_VALUE_EQUITY": ("owners_equity", "ratio", 15),
    "RT_VALUE_EV_EBITDA": ("ev_to_ebitda", "ratio", 18),
    "RT_VALUE_MARKET_CAP": ("market_cap", "ratio", 19),
    "RT_VALUE_OUTSTANDING_SHARES": ("outstanding_shares", "ratio", 13),
    "RT_VALUE_PB": ("pb_ratio", "ratio", 19),
    "RT_VALUE_PE": ("pe_ratio", "ratio", 19),
    "RT_VALUE_PS": ("ps_ratio", "ratio", 18),
    "RT_VALUE_P_CF": ("price_to_cash_flow", "ratio", 19),
}

# The ids something actually reads today: the dashboard's nine charts plus both
# scoring rubrics. These are the ones that must be right for anything to work;
# the rest are verified extras that a future bank or securities rubric can use
# without another discovery pass.
NEEDED = (
    "BS_ADVANCES_FROM_CUSTOMERS",
    "BS_CASH",
    "BS_CASH_AND_PRECIOUS_METALS",
    "BS_CASH_EQUIVALENTS",
    "BS_CHARTER_CAPITAL",
    "BS_CONSTRUCTION_IN_PROGRESS",
    "BS_EQUITY",
    "BS_FIXED_ASSETS",
    "BS_INVENTORIES",
    "BS_LONG_TERM_ADVANCES_FROM_CUSTOMERS",
    "BS_LONG_TERM_BORROWINGS",
    "BS_LONG_TERM_INVESTMENTS",
    "BS_LONG_TERM_PRODUCTION_IN_PROGRESS",
    "BS_LONG_TERM_RECEIVABLES",
    "BS_LONG_TERM_TRADE_RECEIVABLES",
    "BS_LONG_TERM_UNEARNED_REVENUE",
    "BS_MINORITY_INTEREST",
    "BS_OWNERS_EQUITY",
    "BS_SHORT_TERM_ASSETS",
    "BS_SHORT_TERM_BORROWINGS",
    "BS_SHORT_TERM_INVESTMENTS",
    "BS_SHORT_TERM_LIABILITIES",
    "BS_SHORT_TERM_RECEIVABLES",
    "BS_SHORT_TERM_UNEARNED_REVENUE",
    "BS_TOTAL_ASSETS",
    "BS_TOTAL_LIABILITIES_AND_EQUITY",
    "BS_TRADE_ACCOUNTS_PAYABLE",
    "BS_TRADE_RECEIVABLES",
    "CF_CASH_AND_CASH_EQUIVALENTS_AT_END_OF_PERIOD",
    "CF_DEPRECIATION_AND_AMORTISATION",
    "CF_NET_CASH_FLOWS_FROM_FINANCING_ACTIVITIES",
    "CF_NET_CASH_FLOWS_FROM_INVESTING_ACTIVITIES",
    "CF_NET_CASH_FLOWS_FROM_OPERATING_ACTIVITIES",
    "CF_PAYMENTS_FOR_FIXED_ASSETS",
    "IS_COST_OF_GOODS_SOLD",
    "IS_FINANCIAL_EXPENSES",
    "IS_FINANCIAL_INCOME",
    "IS_GENERAL_AND_ADMINISTRATIVE_EXPENSES",
    "IS_GROSS_PROFIT",
    "IS_INTEREST_EXPENSES",
    "IS_NET_PROFIT_AFTER_TAX",
    "IS_NET_REVENUE",
    "IS_OTHER_PROFIT",
    "IS_PROFIT_AFTER_TAX_FOR_SHAREHOLDERS_OF_PARENT_COMPANY",
    "IS_PROFIT_BEFORE_TAX",
    "IS_SELLING_EXPENSES",
    "IS_SHARE_OF_ASSOCIATES_AND_JOINT_VENTURES_RESULT",
    "IS_SHARE_OF_PROFIT_IN_ASSOCIATES_AND_JOINT_VENTURES",
    "RT_VALUE_OUTSTANDING_SHARES",
    "RT_VALUE_PB",
    "RT_VALUE_PE",
)

# Needed, but with no free equivalent. Kept as an explicit list so it is a known
# gap rather than a silently missing key.
NO_FREE_EQUIVALENT = (
    # free reports 0 where the sponsor tier reports the real figure (FPT
    # 2026-Q2: 20,128bn vs 0). Not a naming problem — a different concept.
    "BS_SHORT_TERM_INVESTMENTS",
)

# Present in FREE but absent from the sponsor-loaded store for all 20 sampled
# symbols, i.e. switching would FILL a chart line that is empty today.
FREE_ONLY = {
    "CF_NET_CASH_FLOWS_FROM_FINANCING_ACTIVITIES": "net_cash_inflows_outflows_from_financing_activities",
}


def free_id(metric_id: str) -> str | None:
    """The free item_id for a sponsor metric_id, or None if there is no mapping."""
    hit = FREE_TO_PAID.get(metric_id)
    return hit[0] if hit else FREE_ONLY.get(metric_id)
